db:
  hostID:
    resolver: environment
    envVarName: M3DB_HOST_ID

  # Note: cannot use type: "m3db_single_node" since sometimes
  # multiple DB nodes spawned using the m3_stack start script
  # and as such the non-seed nodes need to point etcd not to
  # localhost but to etcd:2379 specifically.
  discovery:
    config:
      service:
        env: default_env
        zone: embedded
        service: m3db
        cacheDir: /var/lib/m3kv
        etcdClusters:
          - zone: embedded
            endpoints:
              - etcd:2379
            auth:
              enabled: true
              username: test
              password: pqrs
      seedNodes:
        initialCluster:
          - hostID: etcd
            endpoint: http://etcd:2380
